# Generated by Django 4.2.5 on 2023-10-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todo_todo_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo_text',
            new_name='text',
        ),
    ]
